const pathroutes = {
  ADMIN: "/admin",
  CLIENT: "/clientinfo",
  FORMPRODUCTAD: "/createproduct",
  INSTRUCTOR: "/instructors",
  CATEGORY: "/categories",
  CREATEDINST: "/createinstructor",
  MODIFY: "/modifycategory/:id",
  MODIFYINST: "/modifyinstructor/:id",
  HOME: "/",
  DETAIL: "/detail/:id",
  FORM: "/create",
  ERROR: "/*",
  PRODUCT: "/product",
  SHOPPINGCART: "/shopping",
  SERVICE: "/services",
  FORMPRODUCT: "/admin/product/create",
  REGISTER: "/register",
  STORE: "/store",
  USER_PROFILE: "/userprofile",
  LOGIN: "/login",
  ADMIN: "/admin",
  ADMINCATEGORY: "/admin/category",
  ADMINCATEGORYCREATE: "/admin/category/create",
  ADMINCATEGORYMODIFY: "admin/category/modify/:id",
  ADMININSTRUCTOR: "/admin/instructor",
  ADMININSTRUCTORCREATE: "/admin/instructor/create",
  ADMININSTRUCTORMODIFY: "/admin/instructor/modify/:id",
  ADMINPRODUCT: "/admin/product/",
  ADMINCLIENT: "/admin/client/",
  ADMINCLIENTPROFILE: "/admin/client/modifyinfo/:id",
};
export default pathroutes;
