const pathroutes = {
  ADMIN: "/admin",
  CLIENT: "/clientinfo",
  FORMPRODUCTAD: "/createproduct",
  INSTRUCTOR: "/instructors",
  CATEGORY: "/categories",
  CREATEDINST: "/createinstructor",
  MODIFY: "/modifycategory/:id",
  MODIFYINST: "/modifyinstructor/:id",
  HOME: "/",
  DETAIL: "/detail/:id",
  FORM: "/create",
  ERROR: "/*",
  PRODUCT: "/product",
  SHOPPINGCART: "/shopping",
  SERVICE: "/services",
  FORMPRODUCT: "/admin/product/create",
  REGISTER: "/register",
  STORE: "/store",
  USER_PROFILE: "/userprofile",
  LOGIN: "/login",
};
export default pathroutes;
