export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const POST_PRODUCT = "POST_PRODUCT";
<<<<<<< HEAD
=======
export const APPLY_FILTER = "APPLY_FILTER";
export const RESET_FILTER = "RESET_FILTER";
export const EMPTY_FILTER = "EMPTY_FILTER";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const PUT_PRODUCT = "PUT_PRODUCT";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const POST_CATEGORY = "POST_CATEGORY";
export const PUT_CATEGORY = "PUT_CATEGORY";
>>>>>>> b68336ff7707904ad082bd0f9e4373e8db4d9637
